version: "3.7"
services:
  nginx:
    build:
      context: infra/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    links:
      - vvgo
    networks:
      - frontend
      - backend

  vvgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vvgo
    expose:
      - "8080"
    networks:
      - backend


networks:
  frontend:
  backend:

