version: "3.7"
services:
  vvgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vvgo
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_ACCESS_KEY: minioadmin
    expose:
      - 8080

  page-cache:
    build:
      context: infra/page-cache
      dockerfile: Dockerfile
    container_name: page-cache
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host

  object-cache:
    build:
      context: infra/object-cache
      dockerfile: Dockerfile
    container_name: object-cache
    environment:
      MINIO_REGION_NAME: us-east-1
      MINIO_CACHE_EXPIRY: 1
      MINIO_CACHE_QUOTA: 99
      MINIO_CACHE_AFTER: 1
    expose:
      - 9000
