version: "3.7"
services:
  page-cache:
    build:
      context: infra/page-cache
      dockerfile: Dockerfile
    container_name: page-cache
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host

  object-cache:
    build:
      context: infra/object-cache
      dockerfile: Dockerfile.development
    container_name: object-cache
    environment:
      MINIO_ACCESS_KEY: vvgo-admin
      MINIO_SECRET_KEY: vvgo-admin
      MINIO_CACHE_EXPIRY: 1
      MINIO_CACHE_QUOTA: 99
      MINIO_CACHE_AFTER: 1
    expose:
      - 9000

  kv-cache:
    build:
      context: infra/kv-cache
      dockerfile: Dockerfile
    container_name: kv-cache
    expose:
      - 6379

  vvgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vvgo
    environment:
      INITIALIZE_STORAGE: "true"
      REDIS_ADDRESS: kv-cache:6379
      STORAGE_MINIO_ENDPOINT: object-cache:9000
      STORAGE_MINIO_ACCESSKEY: vvgo-admin
      STORAGE_MINIO_SECRETKEY: vvgo-admin
      API_LISTEN_ADDRESS: :8080
    expose:
      - 8080
